### ISSUE TITLE
local.js is missing at /scripts/

### ISSUE THREAD

**Issue by srenzo** [hadimichael/V-Tracker#1]
Hello Hadi,

First I want to congratulate you for this marvelous app ! Very interesting approach.

Occurs that I'm trying to replicate it to learn a little bit more about smartphone's web resources like GPS and Compass, etc (V-Tracker stuffs) but I couldn't find the local.js file that is referenced by index.html ...

Could you send it to me ?

Best regards !

**Comment by hdmchl** [comment]
Thanks. What are you working on exactly? And for what purpose?

I haven't touched this code in years... but if I recall correctly, I used `local.js` to hide a google maps api key. The application should run without it, you just won't be able to visualise routes on a map. Have you tried to manually enter your API key?

That being said, I'll have a look over the weekend and see if I can find the original file. The data-structure would make integration easier for you.

**Comment by srenzo** [comment]
Hello Hadi,

I just realized that and tried my api key but now I'm stacked with a
whitelist something . I suspect that is because my cordova 4.0 version . 

But I'm very thankful for your quick response on this !!!

I'm trying to put a smartphone tracking intelligence + ODB2 car acquisition
code to work together but I do need some reliable measurement way to realize
when the hard accelerations and hard breaks occurs - with your approach on
the V-TRACKER, by fusing the accelerometer, the gps, the gyroscope and
compass data by building a model of analysis is what I was looking for !!!

I will appreciate any other help from you and if you want I can maintain you
up-to-date about my progress or not !

Best regards !
